### ISSUE TITLE
Could not find or load main class org.openqa.grid.selenium.GridLauncherV3

### ISSUE THREAD

**Issue by sunilvasudevan** [jabbrwcky/selenium-api#4]
I tried to start selenium server using the selenium-api jar and provided the -servlets option as well... it is throwing error: Could not find or load main class org.openqa.grid.selenium.GridLauncherV3
Observation: 
1. Tried to start the server without selenium-api jar and no custom servlets provided. Server started and working fine.
2. Tried to start the selenium server with selenium-api jar and provided custom servlets option. Failed to start server. Exception:  Could not find or load main class org.openqa.grid.selenium.GridLauncherV3

Command: java -cp selenium-standalone-3-11.jar:selenium-api.jar org.openqa.grid.selenium.GridLauncherV3 \ -servlets com.xing.qa.selenium.grid.hub.Console -role hub

Thanks
Sunil

**Comment by mstefan7** [comment]
`java -cp selenium-server-standalone-3.11.0.jar:selenium-api.jar org.openqa.grid.selenium.GridLauncherV3 -servlets com.xing.qa.selenium.grid.hub.Console -role hub`

This one works for me like a charm. Can you try without the backslash you have in the command?

**Comment by rkieft** [comment]
@sunilvasudevan probably a bit to late for my respons but I have noticed that there is a difference when starting the grid on Windows or Linux.
If you are using Windows operation system please use the ; instead of a :
That might solve your problem.
